force-app/main/default/objects/Product_Management__c/Product_Management__c.object-meta.xml
<CustomObject>
    <label>Product Management</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Management__c/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <label>ATM Fee in other currencies</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Management__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Management__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UIElementDataControllerTest.cls
@isTest
public class UIElementDataControllerTest {
	@testSetup static void setup() {
    	List<Account> testAccts = new List<Account>();
        for(Integer i=0;i<2;i++) {
            testAccts.add(new Account(Name = 'TestAcct'+i));
        }
        insert testAccts;
        List<Contact> testConts = new List<Contact>();
        for(Account acc: testAccts){
            testConts.add(new Contact(FirstName='Jason',LastName='Smith',AccountId=acc.Id,
                                      email='js@test.com',Product__c='Standard',Home_Country__c = 'IT'));
        }
       	insert testConts;
        List<Case> caseRec = new List<Case>();
        for(Contact newC : testConts){
          	caseRec.add(new Case(Status='New',Subject='Test Class',Origin = 'Email', ContactId=newC.Id));
        }
        Insert caseRec;
        
        List<Product_Management__c> prdManagement = new List<Product_Management__c>();
        prdManagement.add(new Product_Management__c(Name = 'Standard',Country__c='IT',Cost_per_Calendar_Month__c='0',
                                                   ATM_Fee_in_other_currencies__c ='1.70%',Card_Replacement_Cost__c=6,
                                                   Unique_Id__c ='Standard_IT'));
        prdManagement.add(new Product_Management__c(Name = 'Standard',Country__c='DE',Cost_per_Calendar_Month__c='0',
                                                   ATM_Fee_in_other_currencies__c ='1.70%',Card_Replacement_Cost__c=6,
                                                   Unique_Id__c ='Standard_DE'));
        Insert prdManagement;
    }
    @isTest static void getUIDataInfoTest() {
        
        Map<String,String> newFilterComponents = new Map<String,String>();
        newFilterComponents.put('Name','Standard');
        newFilterComponents.put('Country__c','IT');
    	UIElementDataController.getUIDataInfo('Product Information',newFilterComponents);
    }
    @isTest static void getUIDataInfoErrorHandlerTest() {
        
        Map<String,String> newFilterComponents = new Map<String,String>();
        newFilterComponents.put('Name','Standard');
        newFilterComponents.put('Country__c','IT');
    	UIElementDataController.getUIDataInfo('Product Information Test',newFilterComponents);
    }
}